Repository AbsaOSS/enceladus, pull requests merged in 2018-11, with the labels that each got.

#12 Add bug report template
  .github/ISSUE_TEMPLATE/bug_report.md
Labels: enhancement

#14 Update absa bintray
  pom.xml
Labels: Enceladus, enhancement, good first issue

#16 Add basic build jenkinsfile
  Jenkinsfile
Labels: feature
