Repository AbsaOSS/enceladus, pull requests merged in 2019-03, with the labels that each got.

#226 Update scalatest and scalatest-maven-plugin versions
  pom.xml
Labels: enhancement

#258 #256 Replace maven enforcer with antrun copy task
  conformance/pom.xml
  menas/pom.xml
  pom.xml
  standardization/pom.xml
Labels: enhancement

#262 Feature/259 include examples in the build
  examples/pom.xml
  examples/src/main/scala/za/co/absa/enceladus/examples/CustomRuleSample1.scala
  examples/src/main/scala/za/co/absa/enceladus/examples/CustomRuleSample2.scala
  examples/src/main/scala/za/co/absa/enceladus/examples/CustomRuleSample3.scala
  examples/src/main/scala/za/co/absa/enceladus/examples/CustomRuleSample4.scala
  examples/src/test/scala/za/co/absa/enceladus/examples/interpreter/rules/custom/UppercaseCustomConformanceRuleSuite.scala
  examples/src/test/scala/za/co/absa/enceladus/examples/interpreter/rules/custom/XPadCustomConformanceRuleSuite.scala
  pom.xml
Labels: enhancement

#265 #27 Old data lingers even if all items in view are deleted
  menas/ui/service/DatasetService.js
  menas/ui/service/MappingTableService.js
  menas/ui/service/SchemaService.js
Labels: Menas, bug

#266 #11 View updates even from canceled edit window
  menas/ui/components/dataset/conformanceRule/upsert.controller.js
  menas/ui/components/dataset/datasetMain.controller.js
  menas/ui/components/mappingTable/mappingTableMain.controller.js
  menas/ui/components/schema/schemaMain.controller.js
Labels: Menas, bug

#268 #156: Configuration of service time zone
  examples/src/main/scala/za/co/absa/enceladus/examples/CustomRuleSample1.scala
  examples/src/main/scala/za/co/absa/enceladus/examples/CustomRuleSample2.scala
  examples/src/main/scala/za/co/absa/enceladus/examples/CustomRuleSample3.scala
  examples/src/main/scala/za/co/absa/enceladus/examples/CustomRuleSample4.scala
Labels: Examples, bug

#272 #186: Epoch standardisation doesn't pass with pattern "epoch"
  testutils/pom.xml
  utils/src/main/scala/za/co/absa/enceladus/utils/types/EnceladusDateParser.scala
  utils/src/main/scala/za/co/absa/enceladus/utils/types/Format.scala
  utils/src/main/scala/za/co/absa/enceladus/utils/validation/DateTimeValidators.scala
  utils/src/test/scala/za/co/absa/enceladus/utils/types/EnceladusDateParserSuite.scala
  utils/src/test/scala/za/co/absa/enceladus/utils/types/FormatSuite.scala
  utils/src/test/scala/za/co/absa/enceladus/utils/validation/DateTimeValidatorsSuite.scala
Labels: Standardization, bug

#274 #157: Add support for offset time zone notation in timestamp format
  utils/src/test/scala/za/co/absa/enceladus/utils/types/EnceladusDateParserSuite.scala
  utils/src/test/scala/za/co/absa/enceladus/utils/validation/DateTimeValidatorsSuite.scala
Labels: Standardization, feature

#275 #206: Refactor timestamp handling classes
  conformance/src/main/scala/za/co/absa/enceladus/conformance/DynamicConformanceJob.scala
  conformance/src/main/scala/za/co/absa/enceladus/conformance/interpreter/DynamicInterpreter.scala
  conformance/src/test/scala/za/co/absa/enceladus/conformance/interpreter/ArrayConformanceSuite.scala
  conformance/src/test/scala/za/co/absa/enceladus/conformance/interpreter/ChorusMockSuite.scala
  conformance/src/test/scala/za/co/absa/enceladus/conformance/interpreter/InterpreterSuite.scala
  conformance/src/test/scala/za/co/absa/enceladus/conformance/interpreter/rules/CastingRuleSuite.scala
  conformance/src/test/scala/za/co/absa/enceladus/conformance/interpreter/rules/NegationRuleSuite.scala
  conformance/src/test/scala/za/co/absa/enceladus/conformance/interpreter/rules/TestRuleBehaviors.scala
  conformance/src/test/scala/za/co/absa/enceladus/conformance/interpreter/rules/custom/CustomRuleSuite.scala
  examples/src/main/scala/za/co/absa/enceladus/examples/CustomRuleSample1.scala
  examples/src/main/scala/za/co/absa/enceladus/examples/CustomRuleSample2.scala
  examples/src/main/scala/za/co/absa/enceladus/examples/CustomRuleSample3.scala
  examples/src/main/scala/za/co/absa/enceladus/examples/CustomRuleSample4.scala
  examples/src/test/scala/za/co/absa/enceladus/examples/interpreter/rules/custom/UppercaseCustomConformanceRuleSuite.scala
  examples/src/test/scala/za/co/absa/enceladus/examples/interpreter/rules/custom/XPadCustomConformanceRuleSuite.scala
  external/fixedWidth/src/main/scala/za/co/absa/enceladus/fixedWidth/types/SparkTypeResolver.scala
  external/fixedWidth/src/test/scala/za/co/absa/enceladus/fixedWidth/FixedWidthRelationSuite.scala
  standardization/src/main/scala/za/co/absa/enceladus/standardization/StandardizationJob.scala
  standardization/src/main/scala/za/co/absa/enceladus/standardization/interpreter/stages/TypeParser.scala
  standardization/src/test/scala/za/co/absa/enceladus/standardization/interpreter/stages/TypeParserSuite.scala
  utils/src/main/scala/za/co/absa/enceladus/utils/time/DateTimePattern.scala
  utils/src/main/scala/za/co/absa/enceladus/utils/time/EnceladusDateTimeParser.scala
  utils/src/main/scala/za/co/absa/enceladus/utils/types/Defaults.scala
  utils/src/main/scala/za/co/absa/enceladus/utils/validation/DateTimeValidator.scala
  utils/src/main/scala/za/co/absa/enceladus/utils/validation/field/FieldValidatorDate.scala
  utils/src/main/scala/za/co/absa/enceladus/utils/validation/field/FieldValidatorTimestamp.scala
  utils/src/test/scala/za/co/absa/enceladus/utils/time/DateTimePatternSuite.scala
  utils/src/test/scala/za/co/absa/enceladus/utils/time/EnceladusDateTimeParserSuite.scala
  utils/src/test/scala/za/co/absa/enceladus/utils/validation/DateTimeValidatorSuite.scala
  utils/src/test/scala/za/co/absa/enceladus/utils/validation/DateTimeValidatorsSuite.scala
Labels: Conformance, Standardization, enhancement
