Repository AbsaOSS/enceladus, pull requests merged in 2019-04, with the labels that each got.

#283 #282 Make tests runnable on remote cluster in distributed mode
  utils/pom.xml
  utils/src/main/resources/application.conf.template
  utils/src/main/scala/za/co/absa/enceladus/utils/testUtils/SparkTestBase.scala
  utils/src/test/scala/za/co/absa/enceladus/utils/transformations/ArrayTransformationsSuite.scala
Labels: enhancement, tests

#322 321 Make values in scopt case class lazy
  testutils/src/main/scala/za/co/absa/enceladus/testutils/e2eSparkRunner/CmdConfig.scala
Labels: tests

#279 #155, #173: Optional timezone meta for timestamp and date standardization
  standardization/src/main/scala/za/co/absa/enceladus/standardization/interpreter/stages/TypeParser.scala
  standardization/src/test/scala/za/co/absa/enceladus/standardization/interpreter/stages/TypeParserSuite.scala
  standardization/src/test/scala/za/co/absa/enceladus/standardization/interpreter/stages/TypeParserSuiteTemplate.scala
  standardization/src/test/scala/za/co/absa/enceladus/standardization/interpreter/stages/TypeParserSuites/TypeParserFromBooleanTypeSuite.scala
  standardization/src/test/scala/za/co/absa/enceladus/standardization/interpreter/stages/TypeParserSuites/TypeParserFromDateTypeSuite.scala
  standardization/src/test/scala/za/co/absa/enceladus/standardization/interpreter/stages/TypeParserSuites/TypeParserFromDecimalTypeSuite.scala
  standardization/src/test/scala/za/co/absa/enceladus/standardization/interpreter/stages/TypeParserSuites/TypeParserFromDoubleTypeSuite.scala
  standardization/src/test/scala/za/co/absa/enceladus/standardization/interpreter/stages/TypeParserSuites/TypeParserFromLongTypeSuite.scala
  standardization/src/test/scala/za/co/absa/enceladus/standardization/interpreter/stages/TypeParserSuites/TypeParserFromStringTypeSuite.scala
  standardization/src/test/scala/za/co/absa/enceladus/standardization/interpreter/stages/TypeParserSuites/TypeParserFromTimestampTypeSuite.scala
  utils/src/main/scala/za/co/absa/enceladus/utils/implicits/StringImplicits.scala
  utils/src/main/scala/za/co/absa/enceladus/utils/implicits/StructFieldImplicits.scala
  utils/src/main/scala/za/co/absa/enceladus/utils/time/DateTimePattern.scala
  utils/src/main/scala/za/co/absa/enceladus/utils/types/Defaults.scala
  utils/src/main/scala/za/co/absa/enceladus/utils/types/TypePattern.scala
  utils/src/test/scala/za/co/absa/enceladus/utils/implicits/StringImplicitsSuite.scala
  utils/src/test/scala/za/co/absa/enceladus/utils/time/DateTimePatternSuite.scala
Labels: Standardization, enhancement, feature
