Repository AbsaOSS/enceladus, pull requests merged in 2020-04, with the labels that each got.

#1268 1266: Wrong license text prevents build
  menas/src/main/scala/za/co/absa/enceladus/menas/models/rest/errors/RequestTimeoutExpiredError.scala
Labels: Menas, bug

#1265 1264: Release notes 2.3.0
  _posts/2020-04-08-release-2.3.0.md
Labels: docs

#1259 Refactoring/730 schemapathvalidator uses return
  utils/src/main/scala/za/co/absa/enceladus/utils/validation/SchemaPathValidator.scala
  utils/src/test/scala/za/co/absa/enceladus/SchemaPathValidatorSuite.scala
Labels: refactoring

#1275 1274: README.md refer to versionless documentation
  README.md
Labels: docs

#1287 1286: Add release notes for v2.3.1
  _posts/2020-04-20-release-2.3.1.md
Labels: docs

#1311 1308: Release 2.4.0
  _posts/2020-04-27-release-2.4.0.md
Labels: docs
