Repository AbsaOSS/enceladus, pull requests merged in 2021-09, with the labels that each got.

#1880 1843 Summary page for properties
  menas/src/main/scala/za/co/absa/enceladus/menas/controllers/LandingPageController.scala
  menas/ui/components/Component.js
  menas/ui/components/app.controller.js
  menas/ui/components/app.view.xml
  menas/ui/components/home/landingPage.controller.js
  menas/ui/components/home/landingPage.view.xml
  menas/ui/components/property/datasetPropertyDetail.controller.js
  menas/ui/components/property/datasetPropertyDetail.view.xml
  menas/ui/components/property/datasetPropertyInfo.fragment.xml
  menas/ui/components/property/datasetPropertyMaster.controller.js
  menas/ui/components/property/datasetPropertyMaster.view.xml
  menas/ui/service/EntityService.js
  menas/ui/service/MessageProvider.js
  menas/ui/service/PropertiesService.js
  menas/ui/service/RestDAO.js
Labels: PR:tested

#1879 Feature/1603 mapping table filtering general
  dao/src/test/scala/za/co/absa/enceladus/dao/rest/JsonSerializerSuite.scala
  data-model/src/main/scala/za/co/absa/enceladus/model/test/factories/MappingTableFactory.scala
  menas/src/main/scala/za/co/absa/enceladus/menas/utils/implicits/package.scala
  menas/src/test/scala/za/co/absa/enceladus/menas/integration/controllers/DatasetApiIntegrationSuite.scala
Labels: PR:tested

#1910 #1909 Increase the limit of columns shown in menas column selection
  menas/ui/components/dataset/conformanceRule/RuleColumnDialog.js
Labels: PR:tested

#1906 1903 Add validation for complex default values in mapping tables on import
  data-model/src/main/scala/za/co/absa/enceladus/model/SchemaField.scala
  data-model/src/test/scala/za/co/absa/enceladus/model/SchemaFieldTest.scala
  menas/src/main/scala/za/co/absa/enceladus/menas/services/MappingTableService.scala
Labels: PR:tested

#1908 Project config and management updates
  .github/CODEOWNERS
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/poc.md
  README.md
  pom.xml
Labels: docs

#1896 1881 HyperConformance enceladus_info_version from payload
  spark-jobs/src/main/scala/za/co/absa/enceladus/conformance/HyperConformance.scala
  spark-jobs/src/main/scala/za/co/absa/enceladus/conformance/HyperConformanceAttributes.scala
  spark-jobs/src/main/scala/za/co/absa/enceladus/conformance/streaming/InfoDateFactory.scala
  spark-jobs/src/main/scala/za/co/absa/enceladus/conformance/streaming/InfoVersionFactory.scala
  spark-jobs/src/test/scala/za/co/absa/enceladus/conformance/interpreter/fixtures/StreamingFixture.scala
  spark-jobs/src/test/scala/za/co/absa/enceladus/conformance/streaming/HyperConformanceIntegrationSuite.scala
  spark-jobs/src/test/scala/za/co/absa/enceladus/conformance/streaming/HyperConformanceMappingIntegrationSuite.scala
  spark-jobs/src/test/scala/za/co/absa/enceladus/conformance/streaming/InfoDateFactorySuite.scala
  spark-jobs/src/test/testData/nestedStructs/conformed_literal_info_col.json
Labels: PR:tested

#1899 #1887 defaultTimestampTimeZone can be source type specific
  examples/src/main/scala/za/co/absa/enceladus/examples/CustomRuleSample4.scala
  spark-jobs/src/main/scala/za/co/absa/enceladus/conformance/interpreter/rules/NegationRuleInterpreter.scala
  spark-jobs/src/main/scala/za/co/absa/enceladus/standardization/StandardizationExecution.scala
  spark-jobs/src/main/scala/za/co/absa/enceladus/standardization/StandardizationJob.scala
  spark-jobs/src/main/scala/za/co/absa/enceladus/standardization/StandardizationPropertiesProvider.scala
  spark-jobs/src/main/scala/za/co/absa/enceladus/standardization/interpreter/StandardizationInterpreter.scala
  spark-jobs/src/main/scala/za/co/absa/enceladus/standardization_conformance/StandardizationAndConformanceJob.scala
  spark-jobs/src/test/scala/za/co/absa/enceladus/standardization/StandardizationFixedWidthSuite.scala
  spark-jobs/src/test/scala/za/co/absa/enceladus/standardization/StandardizationJsonSuite.scala
  spark-jobs/src/test/scala/za/co/absa/enceladus/standardization/StandardizationParquetSuite.scala
  spark-jobs/src/test/scala/za/co/absa/enceladus/standardization/StandardizationRerunSuite.scala
  spark-jobs/src/test/scala/za/co/absa/enceladus/standardization/csv/NullValueStandardizationCsvSuite.scala
  spark-jobs/src/test/scala/za/co/absa/enceladus/standardization/csv/WhiteSpaceStandardizationCsvSuite.scala
  spark-jobs/src/test/scala/za/co/absa/enceladus/standardization/interpreter/CounterPartySuite.scala
  spark-jobs/src/test/scala/za/co/absa/enceladus/standardization/interpreter/DateTimeSuite.scala
  spark-jobs/src/test/scala/za/co/absa/enceladus/standardization/interpreter/SampleDataSuite.scala
  spark-jobs/src/test/scala/za/co/absa/enceladus/standardization/interpreter/StandardizationInterpreterSuite.scala
  spark-jobs/src/test/scala/za/co/absa/enceladus/standardization/interpreter/StandardizationInterpreter_ArraySuite.scala
  spark-jobs/src/test/scala/za/co/absa/enceladus/standardization/interpreter/StandardizationInterpreter_BinarySuite.scala
  spark-jobs/src/test/scala/za/co/absa/enceladus/standardization/interpreter/StandardizationInterpreter_DateSuite.scala
  spark-jobs/src/test/scala/za/co/absa/enceladus/standardization/interpreter/StandardizationInterpreter_DecimalSuite.scala
  spark-jobs/src/test/scala/za/co/absa/enceladus/standardization/interpreter/StandardizationInterpreter_FractionalSuite.scala
  spark-jobs/src/test/scala/za/co/absa/enceladus/standardization/interpreter/StandardizationInterpreter_IntegralSuite.scala
  spark-jobs/src/test/scala/za/co/absa/enceladus/standardization/interpreter/StandardizationInterpreter_TimestampSuite.scala
  spark-jobs/src/test/scala/za/co/absa/enceladus/standardization/interpreter/StdInterpreterSuite.scala
  spark-jobs/src/test/scala/za/co/absa/enceladus/standardization/interpreter/stages/TypeParserSuite.scala
  utils/src/main/scala/za/co/absa/enceladus/utils/types/Defaults.scala
  utils/src/main/scala/za/co/absa/enceladus/utils/types/DefaultsByFormat.scala
  utils/src/test/resources/application.conf
  utils/src/test/scala/za/co/absa/enceladus/utils/types/DefaultsByFormatSuite.scala
  utils/src/test/scala/za/co/absa/enceladus/utils/types/DefaultsSuite.scala
Labels: PR:tested

#1916 #1887 defaultTimestampTimeZone can be source type specific
  utils/src/main/scala/za/co/absa/enceladus/utils/types/DefaultsByFormat.scala
  utils/src/test/resources/application.conf
  utils/src/test/scala/za/co/absa/enceladus/utils/types/DefaultsByFormatSuite.scala
Labels: PR:no testing needed

#1900 #172 Save original timezone information in metadata file
  pom.xml
  spark-jobs/pom.xml
  spark-jobs/src/main/scala/za/co/absa/enceladus/common/plugin/menas/EventListenerMenas.scala
  spark-jobs/src/main/scala/za/co/absa/enceladus/conformance/ConformanceExecution.scala
  spark-jobs/src/main/scala/za/co/absa/enceladus/standardization/StandardizationExecution.scala
  spark-jobs/src/test/scala/za/co/absa/enceladus/conformance/interpreter/InterpreterSuite.scala
  spark-jobs/src/test/scala/za/co/absa/enceladus/standardization/StandardizationExecutionSuite.scala
  utils/pom.xml
  utils/src/main/scala/za/co/absa/enceladus/utils/fs/FileSystemUtils.scala
Labels: PR:tested

#1912 #1894 `HadoopFsPersistenceFactory` - adding Spline S3 write support
  spark-jobs/src/main/resources/spline.properties.template
  spark-jobs/src/main/scala/za/co/absa/enceladus/spline/persistence/HadoopFsDataLineageWriter.scala
  spark-jobs/src/main/scala/za/co/absa/enceladus/spline/persistence/HadoopFsPersistenceFactory.scala
Labels: PR:tested

#1890 Merging Release 2.23. 0 into develop ver 3
  .editorconfig
  .gitattributes
  dao/pom.xml
  dao/src/main/scala/za/co/absa/enceladus/dao/auth/MenasCredentials.scala
  data-model/pom.xml
  data-model/src/main/scala/za/co/absa/enceladus/model/Dataset.scala
  data-model/src/main/scala/za/co/absa/enceladus/model/Validation.scala
  data-model/src/main/scala/za/co/absa/enceladus/model/menas/audit/Auditable.scala
  data-model/src/test/scala/za/co/absa/enceladus/model/menas/audit/AuditableTest.scala
  examples/pom.xml
  menas/pom.xml
  menas/ui/components/dataset/addDataset.fragment.xml
  menas/ui/components/dataset/datasetDetail.controller.js
  menas/ui/components/dataset/datasetInfo.fragment.xml
  menas/ui/components/login/loginDetail.controller.js
  menas/ui/css/style.css
  menas/ui/generic/formatters.js
  menas/ui/service/EntityDialog.js
  menas/ui/service/EntityService.js
  menas/ui/service/EntityValidationService.js
  migrations-cli/pom.xml
  migrations/pom.xml
  plugins-api/pom.xml
  plugins-builtin/pom.xml
  plugins-builtin/src/main/scala/za/co/absa/enceladus/plugins/builtin/common/mq/kafka/InfoProducerKafka.scala
  plugins-builtin/src/main/scala/za/co/absa/enceladus/plugins/builtin/common/mq/kafka/KafkaConnectionParams.scala
  plugins-builtin/src/main/scala/za/co/absa/enceladus/plugins/builtin/common/mq/kafka/KafkaSecurityParams.scala
  plugins-builtin/src/main/scala/za/co/absa/enceladus/plugins/builtin/common/mq/kafka/SchemaRegistrySecurityParams.scala
  plugins-builtin/src/test/scala/za/co/absa/enceladus/plugins/buildin/kafka/KafkaPluginSuite.scala
  plugins-builtin/src/test/scala/za/co/absa/enceladus/plugins/builtin/errorsender/mq/KafkaErrorSenderPluginSuite.scala
  pom.xml
  rest-api/pom.xml
  rest-api/src/main/scala/za/co/absa/enceladus/rest_api/services/DatasetService.scala
  rest-api/src/test/scala/za/co/absa/enceladus/rest_api/integration/controllers/DatasetApiIntegrationSuite.scala
  rest-api/src/test/scala/za/co/absa/enceladus/rest_api/services/DatasetServiceTest.scala
  scripts/cmd/_run_enceladus.cmd
  spark-jobs/pom.xml
  spark-jobs/src/main/resources/reference.conf
  spark-jobs/src/main/scala/za/co/absa/enceladus/common/CommonJobExecution.scala
  spark-jobs/src/main/scala/za/co/absa/enceladus/common/Constants.scala
  spark-jobs/src/main/scala/za/co/absa/enceladus/standardization/interpreter/stages/TypeParser.scala
  spark-jobs/src/test/scala/za/co/absa/enceladus/standardization/StandardizationParquetSuite.scala
  utils/pom.xml
  utils/src/main/scala/za/co/absa/enceladus/utils/types/TypedStructField.scala
Labels: PR:no testing needed
