Repository AbsaOSS/enceladus, pull requests merged in 2021-01, with the labels that each got.

#1636 1634: Little project fixes - optional
  pom.xml
Labels: under discussion

#1628 1570 Update dataset creat, edit and export methods
  data-model/src/main/scala/za/co/absa/enceladus/model/Dataset.scala
  data-model/src/test/scala/za/co/absa/enceladus/model/DatasetTest.scala
  menas/src/main/scala/za/co/absa/enceladus/menas/services/DatasetService.scala
  menas/src/test/scala/za/co/absa/enceladus/menas/integration/controllers/DatasetApiIntegrationSuite.scala
Labels: test ran

#1639 1638 Fix validation of conformance rules on import entity
  menas/src/main/scala/za/co/absa/enceladus/menas/services/DatasetService.scala
Labels: test ran

#1607 1434 Add new docker properties
  .gitignore
  menas/Dockerfile
  menas/pom.xml
  menas/src/main/resources/docker.properties.template
  menas/src/main/resources/docker/envoy/Dockerfile
  menas/src/main/resources/docker/envoy/envoy.yaml
  menas/src/main/resources/docker/envoy/start_envoy.sh
  menas/src/main/resources/docker/server.xml
  menas/src/main/resources/docker/start_menas.sh
  menas/src/main/resources/start_menas.sh
  pom.xml
Labels: Menas, cloud

#1649 713 Add favicon
  menas-web/ui/favicon.ico
  menas-web/ui/index.html
Labels: test ran
