Repository AbsaOSS/enceladus, pull requests merged in 2021-11, with the labels that each got.

#1948 1904 validate mapping table additional fields
  data-model/src/main/scala/za/co/absa/enceladus/model/conformanceRule/package.scala
  menas/src/main/scala/za/co/absa/enceladus/menas/services/DatasetService.scala
  menas/src/test/scala/za/co/absa/enceladus/menas/services/DatasetServiceTest.scala
  spark-jobs/src/main/scala/za/co/absa/enceladus/conformance/interpreter/DynamicInterpreter.scala
  spark-jobs/src/main/scala/za/co/absa/enceladus/conformance/interpreter/rules/mapping/MappingRuleInterpreterBroadcast.scala
  spark-jobs/src/main/scala/za/co/absa/enceladus/conformance/interpreter/rules/mapping/MappingRuleInterpreterGroupExplode.scala
Labels: PR:tested

#1969 #1968: Release standardized dataframe after its saving in the combined
  spark-jobs/src/main/scala/za/co/absa/enceladus/standardization_conformance/StandardizationAndConformanceJob.scala
Labels: PR:no testing needed

#1967 1966 Fix missing control checkpoint in MappingTable CR
  menas/ui/components/dataset/conformanceRule/MappingConformanceRule/add.fragment.xml
  menas/ui/components/dataset/conformanceRule/MappingConformanceRule/outputColumns.fragment.xml
Labels: PR:tested

#1962 1959 Add local and S3 keytabs to --files in spark-submit
  scripts/bash/run_enceladus.sh
Labels: PR:tested

#1933 1898 Conformed columns for enceladus_info_version
  data-model/src/main/scala/za/co/absa/enceladus/model/ConformedSchema.scala
  data-model/src/test/scala/za/co/absa/enceladus/model/ConformedSchemaTest.scala
  spark-jobs/src/main/scala/za/co/absa/enceladus/conformance/HyperConformance.scala
  spark-jobs/src/main/scala/za/co/absa/enceladus/conformance/streaming/InfoVersionFactory.scala
  spark-jobs/src/test/scala/za/co/absa/enceladus/conformance/interpreter/fixtures/StreamingFixture.scala
  spark-jobs/src/test/scala/za/co/absa/enceladus/conformance/streaming/HyperConformanceIntegrationSuite.scala
  spark-jobs/src/test/testData/nestedStructs/conformed_literal_conf_info_col.json
Labels: PR:tested

#1970 1938 MappingCR without join a condition
  menas/ui/components/dataset/conformanceRule/ConformanceRuleDialog.js
  menas/ui/components/dataset/conformanceRule/ConformanceRuleForm.js
  menas/ui/components/dataset/conformanceRule/MappingConformanceRule/joinConditions.fragment.xml
  menas/ui/components/mappingTable/filterEdit/FilterEdit.js
  menas/ui/service/EntityDialog.js
  spark-jobs/src/test/scala/za/co/absa/enceladus/conformance/interpreter/rules/RulesSuite.scala
  utils/src/main/scala/za/co/absa/enceladus/utils/broadcast/LocalMappingTable.scala
  utils/src/test/scala/za/co/absa/enceladus/utils/broadcast/BroadcastUtilsSuite.scala
  utils/src/test/scala/za/co/absa/enceladus/utils/broadcast/LocalMappingTableSuite.scala
Labels: PR:tested

#1975 #1974: Conformance doesn't add the Info... columns
  spark-jobs/src/main/scala/za/co/absa/enceladus/common/CommonJobExecution.scala
  spark-jobs/src/main/scala/za/co/absa/enceladus/conformance/ConformanceExecution.scala
  spark-jobs/src/main/scala/za/co/absa/enceladus/standardization/StandardizationExecution.scala
Labels: PR:tested

#1979 #1978 icons mixup corrected for filter edit
  menas/ui/components/mappingTable/filterEdit/filterTreeEdit.fragment.xml
  menas/ui/service/FilterTreeUtils.js
Labels: PR:tested

#1971 1954 Fix mt conformance rule import validation ignoring structs
  menas/src/main/scala/za/co/absa/enceladus/menas/services/DatasetService.scala
  menas/src/main/scala/za/co/absa/enceladus/menas/services/VersionedModelService.scala
  menas/src/test/scala/za/co/absa/enceladus/menas/services/DatasetServiceTest.scala
Labels: PR:tested

#1982 #1981 MCR title missing bugfix
  menas/ui/components/dataset/conformanceRule/MappingConformanceRule/display.fragment.xml
Labels: PR:tested

#1980 #1867 filter from config removed, including tests.
  spark-jobs/src/main/scala/za/co/absa/enceladus/conformance/config/FilterFromConfig.scala
  spark-jobs/src/main/scala/za/co/absa/enceladus/conformance/interpreter/rules/mapping/CommonMappingRuleInterpreter.scala
  spark-jobs/src/test/resources/application.conf
  spark-jobs/src/test/scala/za/co/absa/enceladus/conformance/config/FilterFromConfigSuite.scala
Labels: PR:tested

#1946 1945 Mapping Rule on s3
  spark-jobs/src/main/scala/za/co/absa/enceladus/conformance/interpreter/DynamicInterpreter.scala
Labels: PR:tested

#1984 1983 Remove faulty whitespaces in keytab name evaluation
  scripts/bash/run_enceladus.sh
Labels: PR:tested

#1986 #1985: Add release notes for v2.26.0
  _posts/2020-09-18-release-2.13.0.md
  _posts/2021-10-24-release-2.25.0.md
  _posts/2021-11-23-release-2.26.0.md
Labels: docs

#1990 #1987: Repartitioning prevents processing of zero size files - ver. 2.26
  .gitignore
  spark-jobs/src/main/scala/za/co/absa/enceladus/common/CommonJobExecution.scala
  spark-jobs/src/test/resources/data/empty/_SUCCESS
  spark-jobs/src/test/scala/za/co/absa/enceladus/common/CommonExecutionSuite.scala
  spark-jobs/src/test/scala/za/co/absa/enceladus/conformance/interpreter/rules/testcasefactories/SimpleTestCaseFactory.scala
Labels: PR:tested

#1991 #1987: Repartitioning prevents processing of zero size files - ver. 2.25
  .gitignore
  spark-jobs/src/main/scala/za/co/absa/enceladus/common/CommonJobExecution.scala
  spark-jobs/src/test/resources/data/empty/_SUCCESS
  spark-jobs/src/test/scala/za/co/absa/enceladus/common/CommonExecutionSuite.scala
  spark-jobs/src/test/scala/za/co/absa/enceladus/conformance/interpreter/rules/testcasefactories/SimpleTestCaseFactory.scala
Labels: PR:tested

#1993 #1992: Add release notes for v2.25.2 and v2.26.1
  _posts/2021-11-25-release-2.25.2.md
  _posts/2021-11-25-release-2.26.1.md
Labels: docs
