Repository AbsaOSS/enceladus, pull requests merged in 2021-04, with the labels that each got.

#1721 1662 Mapping Multiple Outputs Frontend
  data-model/src/main/scala/META-INF/MANIFEST.MF
  data-model/src/main/scala/za/co/absa/enceladus/model/Dataset.scala
  menas/src/main/scala/za/co/absa/enceladus/menas/repositories/DatasetMongoRepository.scala
  menas/ui/components/dataset/conformanceRule/ConformanceRule.js
  menas/ui/components/dataset/conformanceRule/ConformanceRuleDialog.js
  menas/ui/components/dataset/conformanceRule/ConformanceRuleForm.js
  menas/ui/components/dataset/conformanceRule/MappingConformanceRule/OutputColumnDialog.js
  menas/ui/components/dataset/conformanceRule/MappingConformanceRule/OutputColumnDialogFactory.js
  menas/ui/components/dataset/conformanceRule/MappingConformanceRule/add.fragment.xml
  menas/ui/components/dataset/conformanceRule/MappingConformanceRule/display.fragment.xml
  menas/ui/components/dataset/conformanceRule/MappingConformanceRule/outputColumnDialog.fragment.xml
  menas/ui/components/dataset/conformanceRule/MappingConformanceRule/outputColumns.fragment.xml
  menas/ui/components/dataset/conformanceRule/MappingConformanceRule/targetSchemaFieldSelector.fragment.xml
  menas/ui/components/dataset/datasetDetail.controller.js
  menas/ui/index.html
  menas/ui/service/SchemaFieldSelector.js
  migrations/src/main/scala/za/co/absa/enceladus/migrations/migrations/MigrationToV1.scala
  migrations/src/main/scala/za/co/absa/enceladus/migrations/migrations/model1/conformanceRule/package.scala
Labels: PR:tested

#1754 #1753 Add ignore white spaces option to csv read
  scripts/bash/run_enceladus.sh
  spark-jobs/src/main/scala/za/co/absa/enceladus/standardization/StandardizationPropertiesProvider.scala
  spark-jobs/src/main/scala/za/co/absa/enceladus/standardization/config/StandardizationConfig.scala
  spark-jobs/src/main/scala/za/co/absa/enceladus/standardization/config/StandardizationConfigParser.scala
  spark-jobs/src/main/scala/za/co/absa/enceladus/standardization_conformance/config/StandardizationConformanceConfig.scala
  spark-jobs/src/test/resources/data/standardization_csv_suite_data_with_white_spaces.csv
  spark-jobs/src/test/scala/za/co/absa/enceladus/standardization/csv/WhiteSpaceStandardizationCsvSuite.scala
Labels: PR:tested

#1740 #1702: Different verification of Dataset properties from setup API and from SparkJobs on execution
  dao/src/main/scala/za/co/absa/enceladus/dao/MenasDAO.scala
  dao/src/main/scala/za/co/absa/enceladus/dao/rest/MenasRestDAO.scala
  dao/src/test/scala/za/co/absa/enceladus/dao/rest/MenasRestDAOSuite.scala
  data-model/src/main/scala/za/co/absa/enceladus/model/Validation.scala
  data-model/src/main/scala/za/co/absa/enceladus/model/properties/PropertyDefinition.scala
  data-model/src/main/scala/za/co/absa/enceladus/model/properties/essentiality/package.scala
  data-model/src/main/scala/za/co/absa/enceladus/model/test/factories/PropertyDefinitionFactory.scala
  data-model/src/test/scala/za/co/absa/enceladus/model/PropertyDefinitionTest.scala
  menas/src/main/scala/za/co/absa/enceladus/menas/MvcConfig.scala
  menas/src/main/scala/za/co/absa/enceladus/menas/controllers/DatasetController.scala
  menas/src/main/scala/za/co/absa/enceladus/menas/controllers/RestExceptionHandler.scala
  menas/src/main/scala/za/co/absa/enceladus/menas/services/DatasetService.scala
  menas/src/main/scala/za/co/absa/enceladus/menas/services/RunService.scala
  menas/src/main/scala/za/co/absa/enceladus/menas/services/VersionedModelService.scala
  menas/src/main/scala/za/co/absa/enceladus/menas/utils/converters/StringToValidationKindConverter.scala
  menas/src/test/scala/za/co/absa/enceladus/menas/integration/controllers/DatasetApiIntegrationSuite.scala
  menas/src/test/scala/za/co/absa/enceladus/menas/integration/repositories/RunRepositoryIntegrationSuite.scala
  menas/src/test/scala/za/co/absa/enceladus/menas/services/DatasetServiceTest.scala
  menas/src/test/scala/za/co/absa/enceladus/menas/services/RunServiceTest.scala
  menas/src/test/scala/za/co/absa/enceladus/menas/services/VersionedModelServiceTest.scala
  menas/src/test/scala/za/co/absa/enceladus/menas/utils/converters/StringToValidationLevelConverterSuite.scala
  spark-jobs/src/main/scala/za/co/absa/enceladus/common/CommonJobExecution.scala
  spark-jobs/src/main/scala/za/co/absa/enceladus/conformance/HyperConformance.scala
  spark-jobs/src/test/scala/za/co/absa/enceladus/common/CommonExecutionSuite.scala
  spark-jobs/src/test/scala/za/co/absa/enceladus/conformance/interpreter/InterpreterSuite.scala
  spark-jobs/src/test/scala/za/co/absa/enceladus/conformance/interpreter/fixtures/NestedStructsFixture.scala
  spark-jobs/src/test/scala/za/co/absa/enceladus/conformance/interpreter/rules/CastingRuleSuite.scala
  spark-jobs/src/test/scala/za/co/absa/enceladus/conformance/interpreter/rules/NegationRuleSuite.scala
  spark-jobs/src/test/scala/za/co/absa/enceladus/conformance/interpreter/rules/TestRuleBehaviors.scala
  spark-jobs/src/test/scala/za/co/absa/enceladus/conformance/interpreter/rules/testcasefactories/NestedTestCaseFactory.scala
  spark-jobs/src/test/scala/za/co/absa/enceladus/conformance/interpreter/rules/testcasefactories/SimpleTestCaseFactory.scala
  utils/src/main/scala/za/co/absa/enceladus/utils/implicits/StringImplicits.scala
  utils/src/main/scala/za/co/absa/enceladus/utils/time/TimeZoneNormalizer.scala
  utils/src/main/scala/za/co/absa/enceladus/utils/validation/ValidationLevel.scala
  utils/src/test/scala/za/co/absa/enceladus/utils/implicits/StringImplicitsSuite.scala
  utils/src/test/scala/za/co/absa/enceladus/utils/validation/ValidationLevelSuite.scala
Labels: PR:tested

#1761 #1757: Updating Windows Helper scripts for DRA default and CSV whitespace trimming
  scripts/cmd/_enceladus_env.template.cmd
  scripts/cmd/_run_enceladus.cmd
  scripts/cmd/run_conformance.cmd
  scripts/cmd/run_standardization.cmd
  scripts/cmd/run_standardization_conformance.cmd
Labels: PR:no testing needed

#1764 #1763: Helper scripts missing description of new switches
  scripts/bash/_print_help.sh
  scripts/cmd/_print_help.cmd
Labels: docs

#1765 #1760: Update documentation on CSV's ignore white space
  _docs/2.0.0/usage/info-file.md
  _docs/2.0.0/usage/run.md
Labels: docs

#1773 #1767: Add release notes for v2.22.0
  _posts/2021-04-23-release-2.22.0.md
Labels: docs

#1775 1774 kafka error test fix (SourcePhase capitalization)
  plugins-builtin/src/test/scala/za/co/absa/enceladus/plugins/builtin/errorsender/mq/KafkaErrorSenderPluginSuite.scala
  utils/src/main/scala/za/co/absa/enceladus/utils/modules/SourcePhase.scala
Labels: PR:no testing needed
