Repository AbsaOSS/enceladus, pull requests merged in 2021-06, with the labels that each got.

#1780 1756 Incorrect stdErrors in array
  pom.xml
  spark-jobs/src/test/scala/za/co/absa/enceladus/standardization/interpreter/StandardizationInterpreter_ArraySuite.scala
  utils/src/main/scala/za/co/absa/enceladus/utils/udf/UDFBuilder.scala
Labels: PR:no testing needed

#1739 1732 Spline 0.6 integration
  menas/ui/components/run/runDetail.view.xml
  menas/ui/css/style.css
  menas/ui/index.html
  menas/ui/package.json
  menas/ui/service/RunRestDAO.js
  menas/ui/service/RunService.js
  rest-api/src/main/resources/application.properties.template
  rest-api/src/main/resources/scheduling/oozie/workflow_template.xml
  rest-api/src/main/scala/za/co/absa/enceladus/rest_api/HDFSConfig.scala
  rest-api/src/main/scala/za/co/absa/enceladus/rest_api/controllers/RunController.scala
  rest-api/src/main/scala/za/co/absa/enceladus/rest_api/repositories/OozieRepository.scala
  rest-api/src/main/scala/za/co/absa/enceladus/rest_api/services/RunService.scala
  rest-api/src/test/resources/application.properties
  rest-api/src/test/scala/za/co/absa/enceladus/rest_api/integration/controllers/RunApiIntegrationSuite.scala
  scripts/bash/enceladus_env.template.sh
  scripts/bash/run_enceladus.sh
  spark-jobs/pom.xml
  spark-jobs/src/main/resources/reference.conf
  spark-jobs/src/main/resources/spline.properties.template
  spark-jobs/src/main/scala/za/co/absa/enceladus/common/Constants.scala
  spark-jobs/src/test/resources/spline.properties
Labels: PR:tested

#1788 #1787: MenasDAO.getDataset backwards compatibility fix
  dao/src/main/scala/za/co/absa/enceladus/dao/MenasDAO.scala
  dao/src/main/scala/za/co/absa/enceladus/dao/rest/MenasRestDAO.scala
  dao/src/test/scala/za/co/absa/enceladus/dao/rest/MenasRestDAOSuite.scala
  menas/src/main/scala/za/co/absa/enceladus/menas/controllers/DatasetController.scala
  utils/src/main/scala/za/co/absa/enceladus/utils/validation/ValidationLevel.scala
  utils/src/test/scala/za/co/absa/enceladus/utils/validation/ValidationLevelSuite.scala
Labels: PR:tested

#1799 #1790: Replace the discontinued Bintray as source of packages
  menas/pom.xml
  menas/ui/3rdParty/cRonstrue/LICENSE
  menas/ui/3rdParty/cRonstrue/cronstrue.min.js
  menas/ui/index.html
  pom.xml
Labels: PR:tested

#1803 cronstrue not being loaded without existing session
  menas/src/main/scala/za/co/absa/enceladus/menas/WebSecurityConfig.scala
Labels: PR:tested

#1805 #1804: Add release notes for v2.22.1, v2.21.1 and v2.20.1
  _posts/2021-06-06-release-2.20.1.md
  _posts/2021-06-06-release-2.21.1.md
  _posts/2021-06-06-release-2.22.1.md
Labels: docs

#1810 #1794 Move CMD_LINE before first usages
  scripts/bash/run_enceladus.sh
Labels: PR:no testing needed

#1811 rat-plugin config for menas in a profile (same as root pom.xml)
  menas/pom.xml
Labels: PR:no testing needed

#1806 #1809 NativeIO removal for windows build
  README.md
  spark-jobs/pom.xml
  utils/pom.xml
  utils/src/test/scala/org/apache/hadoop/io/nativeio/NativeIO.java
Labels: PR:tested

#1813 #1812 Jersey-server fix on Tomcat
  Jenkinsfile
  rest-api/pom.xml
Labels: PR:tested

#1758 Feature/1755 spark3.1
  plugins-builtin/pom.xml
  pom.xml
  spark-jobs/src/main/scala/za/co/absa/enceladus/common/SparkCompatibility.scala
  spark-jobs/src/test/resources/interpreter/mappingCases/array1Schema.txt
  spark-jobs/src/test/resources/interpreter/mappingCases/array2Schema.txt
  spark-jobs/src/test/resources/interpreter/mappingCases/array3Schema.txt
  spark-jobs/src/test/resources/interpreter/mappingCases/array4Schema.txt
  spark-jobs/src/test/resources/interpreter/mappingCases/array5Schema.txt
  spark-jobs/src/test/resources/interpreter/mappingCases/array6Schema.txt
  spark-jobs/src/test/resources/interpreter/mappingCases/array7Schema.txt
  spark-jobs/src/test/resources/interpreter/mappingCases/multiple_output/array1SchemaMulti.txt
  spark-jobs/src/test/resources/interpreter/mappingCases/multiple_output/array2SchemaMulti.txt
  spark-jobs/src/test/resources/interpreter/mappingCases/multiple_output/array3SchemaMulti.txt
  spark-jobs/src/test/resources/interpreter/mappingCases/multiple_output/array4SchemaMulti.txt
  spark-jobs/src/test/resources/interpreter/mappingCases/multiple_output/array5SchemaMulti.txt
  spark-jobs/src/test/scala/za/co/absa/enceladus/conformance/interpreter/rules/mapping/MappingGroupExplodeSuite.scala
  spark-jobs/src/test/scala/za/co/absa/enceladus/conformance/interpreter/rules/mapping/MappingInterpreterSuite.scala
  spark-jobs/src/test/scala/za/co/absa/enceladus/standardization/interpreter/stages/TypeParser_FromBooleanTypeSuite.scala
  spark-jobs/src/test/scala/za/co/absa/enceladus/standardization/interpreter/stages/TypeParser_FromDateTypeSuite.scala
  spark-jobs/src/test/scala/za/co/absa/enceladus/standardization/interpreter/stages/TypeParser_FromDecimalTypeSuite.scala
  spark-jobs/src/test/scala/za/co/absa/enceladus/standardization/interpreter/stages/TypeParser_FromDoubleTypeSuite.scala
  spark-jobs/src/test/scala/za/co/absa/enceladus/standardization/interpreter/stages/TypeParser_FromLongTypeSuite.scala
  spark-jobs/src/test/scala/za/co/absa/enceladus/standardization/interpreter/stages/TypeParser_FromStringTypeSuite.scala
  spark-jobs/src/test/scala/za/co/absa/enceladus/standardization/interpreter/stages/TypeParser_FromTimestampTypeSuite.scala
  utils/src/main/scala/za/co/absa/enceladus/utils/udf/UDFBuilder.scala
  utils/src/test/scala/za/co/absa/enceladus/utils/ExplosionSuite.scala
Labels: PR:no testing needed

#1824 strip blank properties fix
  menas/ui/service/EntityService.js
Labels: PR:tested

#1826 strip blank properties fix for 2.22
  menas/ui/service/EntityService.js
Labels: PR:tested

#1827 strip blank properties fix backport to 2.20
  menas/ui/service/EntityService.js
Labels: PR:tested

#1822 1820 Fix auditable message for Dataset Properties
  data-model/src/main/scala/za/co/absa/enceladus/model/Dataset.scala
  data-model/src/main/scala/za/co/absa/enceladus/model/menas/audit/Auditable.scala
  data-model/src/test/scala/za/co/absa/enceladus/model/menas/audit/AuditableTest.scala
Labels: PR:tested

#1825 strip blank properties fix for 2.21
  menas/ui/service/EntityService.js
Labels: PR:tested
