Repository AbsaOSS/enceladus, pull requests merged in 2021-07, with the labels that each got.

#1832 1814 Read Menas Credentials and Keytab from S3
  dao/src/main/scala/za/co/absa/enceladus/dao/auth/MenasCredentials.scala
Labels: PR:tested

#1841 #1836: Standardization ignores timezone metadata for timestamp type in case the source is already timestamp
  spark-jobs/src/main/scala/za/co/absa/enceladus/standardization/interpreter/stages/TypeParser.scala
  spark-jobs/src/test/scala/za/co/absa/enceladus/standardization/StandardizationParquetSuite.scala
  utils/src/main/scala/za/co/absa/enceladus/utils/types/TypedStructField.scala
Labels: PR:tested

#1840 #1836: Standardization ignores timezone metadata for timestamp type in case the source is already timestamp (2.21)
  spark-jobs/src/main/scala/za/co/absa/enceladus/standardization/interpreter/stages/TypeParser.scala
  spark-jobs/src/test/scala/za/co/absa/enceladus/standardization/StandardizationParquetSuite.scala
  utils/src/main/scala/za/co/absa/enceladus/utils/types/TypedStructField.scala
Labels: PR:tested

#1823 1819 Fix properties warnings not being logged in spark-jobs
  data-model/src/main/scala/za/co/absa/enceladus/model/Validation.scala
  menas/src/main/scala/za/co/absa/enceladus/menas/services/DatasetService.scala
  menas/src/test/scala/za/co/absa/enceladus/menas/integration/controllers/DatasetApiIntegrationSuite.scala
  menas/src/test/scala/za/co/absa/enceladus/menas/services/DatasetServiceTest.scala
  spark-jobs/src/main/scala/za/co/absa/enceladus/common/CommonJobExecution.scala
Labels: PR:tested

#1839 #1808SparkVersionGuard: For Spark 3, min version = 3.0.0
  spark-jobs/src/main/scala/za/co/absa/enceladus/common/SparkCompatibility.scala
Labels: PR:no testing needed

#1846 #1844: When saving a dataset with undefined recommended property show a warning dialog (2.21)
  menas/ui/service/EntityDialog.js
  menas/ui/service/EntityValidationService.js
Labels: PR:tested

#1847 #1844: When saving a dataset with undefined recommended property show a warning dialog
  menas/ui/service/EntityDialog.js
  menas/ui/service/EntityValidationService.js
Labels: PR:tested

#1848 1819 for 2.21 - Fix properties warnings not being logged in spark-jobs
  data-model/src/main/scala/za/co/absa/enceladus/model/Validation.scala
  menas/src/main/scala/za/co/absa/enceladus/menas/services/DatasetService.scala
  menas/src/test/scala/za/co/absa/enceladus/menas/integration/controllers/DatasetApiIntegrationSuite.scala
  menas/src/test/scala/za/co/absa/enceladus/menas/services/DatasetServiceTest.scala
  spark-jobs/src/main/scala/za/co/absa/enceladus/common/CommonJobExecution.scala
Labels: PR:tested

#1845 1842 Dataset Dialog - properties editing update
  menas/ui/components/dataset/addDataset.fragment.xml
  menas/ui/css/style.css
Labels: PR:tested

#1850 1842 Dataset Dialog - properties editing update for 2.22
  menas/ui/components/dataset/addDataset.fragment.xml
  menas/ui/css/style.css
Labels: PR:tested

#1856 #1855: Add release notes for v2.21.2
  _posts/2021-07-17-release-2.21.2.md
Labels: docs

#1828 1807 Add schema registry security params
  plugins-builtin/src/main/scala/za/co/absa/enceladus/plugins/builtin/common/mq/kafka/InfoProducerKafka.scala
  plugins-builtin/src/main/scala/za/co/absa/enceladus/plugins/builtin/common/mq/kafka/KafkaConnectionParams.scala
  plugins-builtin/src/main/scala/za/co/absa/enceladus/plugins/builtin/common/mq/kafka/KafkaSecurityParams.scala
  plugins-builtin/src/main/scala/za/co/absa/enceladus/plugins/builtin/common/mq/kafka/SchemaRegistrySecurityParams.scala
  plugins-builtin/src/test/scala/za/co/absa/enceladus/plugins/buildin/kafka/KafkaPluginSuite.scala
  plugins-builtin/src/test/scala/za/co/absa/enceladus/plugins/builtin/errorsender/mq/KafkaErrorSenderPluginSuite.scala
  spark-jobs/src/main/resources/reference.conf
  spark-jobs/src/main/scala/za/co/absa/enceladus/common/Constants.scala
Labels: PR:tested

#1849 1819 for 2.22.2 - Fix properties warnings not being logged in spark-jobs
  data-model/src/main/scala/za/co/absa/enceladus/model/Validation.scala
  menas/src/main/scala/za/co/absa/enceladus/menas/services/DatasetService.scala
  menas/src/test/scala/za/co/absa/enceladus/menas/integration/controllers/DatasetApiIntegrationSuite.scala
  menas/src/test/scala/za/co/absa/enceladus/menas/services/DatasetServiceTest.scala
  spark-jobs/src/main/scala/za/co/absa/enceladus/common/CommonJobExecution.scala
Labels: PR:tested

#1851 Feature/1705 show properties missing on dataset main page
  menas/ui/components/dataset/datasetDetail.controller.js
  menas/ui/components/dataset/datasetInfo.fragment.xml
  menas/ui/css/style.css
  menas/ui/generic/formatters.js
Labels: PR:tested

#1859 gitflow maven plugin update 1.16.0
  dao/pom.xml
  data-model/pom.xml
  examples/pom.xml
  menas/pom.xml
  migrations-cli/pom.xml
  migrations/pom.xml
  plugins-api/pom.xml
  plugins-builtin/pom.xml
  pom.xml
  spark-jobs/pom.xml
  utils/pom.xml
Labels: PR:no testing needed

#1854 #1853: Remove the warning of wrong browser type and version in Menas
  menas/ui/components/login/loginDetail.controller.js
Labels: PR:tested

#1838 #1818 errCol added in Conformance is not Nullable
  spark-jobs/src/main/resources/reference.conf
  spark-jobs/src/main/scala/za/co/absa/enceladus/common/ErrorColNormalization.scala
  spark-jobs/src/main/scala/za/co/absa/enceladus/conformance/ConformancePropertiesProvider.scala
  spark-jobs/src/main/scala/za/co/absa/enceladus/conformance/HyperConformance.scala
  spark-jobs/src/main/scala/za/co/absa/enceladus/conformance/interpreter/DynamicInterpreter.scala
  spark-jobs/src/main/scala/za/co/absa/enceladus/conformance/interpreter/FeatureSwitches.scala
  spark-jobs/src/main/scala/za/co/absa/enceladus/standardization/StandardizationExecution.scala
  spark-jobs/src/main/scala/za/co/absa/enceladus/standardization/interpreter/StandardizationInterpreter.scala
  spark-jobs/src/test/resources/interpreter/mappingCases/multiple_output/simpleMultiOutSchema.txt
  spark-jobs/src/test/scala/za/co/absa/enceladus/common/error/ErrorMessageFactory.scala
  spark-jobs/src/test/scala/za/co/absa/enceladus/conformance/interpreter/fixtures/StreamingFixture.scala
  spark-jobs/src/test/scala/za/co/absa/enceladus/conformance/interpreter/rules/mapping/MappingGroupExplodeSuite.scala
  spark-jobs/src/test/scala/za/co/absa/enceladus/conformance/interpreter/rules/mapping/MappingInterpreterSuite.scala
  spark-jobs/src/test/scala/za/co/absa/enceladus/conformance/interpreter/rules/mapping/MappingRuleBroadcastSuite.scala
  spark-jobs/src/test/scala/za/co/absa/enceladus/conformance/interpreter/rules/mapping/MappingRuleSuite.scala
  spark-jobs/src/test/scala/za/co/absa/enceladus/conformance/interpreter/rules/testcasefactories/NestedTestCaseFactory.scala
  spark-jobs/src/test/scala/za/co/absa/enceladus/conformance/interpreter/rules/testcasefactories/SimpleTestCaseFactory.scala
  spark-jobs/src/test/scala/za/co/absa/enceladus/standardization/interpreter/StandardizationInterpreterSuite.scala
  spark-jobs/src/test/scala/za/co/absa/enceladus/standardization/interpreter/StandardizationInterpreter_ArraySuite.scala
  spark-jobs/src/test/scala/za/co/absa/enceladus/standardization/interpreter/StdInterpreterSuite.scala
  utils/src/main/scala/za/co/absa/enceladus/utils/explode/ExplodeTools.scala
  utils/src/main/scala/za/co/absa/enceladus/utils/implicits/DataFrameImplicits.scala
  utils/src/test/scala/za/co/absa/enceladus/utils/ExplosionSuite.scala
  utils/src/test/scala/za/co/absa/enceladus/utils/implicits/DataFrameImplicitsSuite.scala
Labels: PR:no testing needed

#1837 #1835: Support multiple date formats in Helper scripts
  .editorconfig
  .gitattributes
  scripts/cmd/_run_enceladus.cmd
Labels: PR:tested
