Repository AbsaOSS/enceladus, pull requests merged in 2022-05, with the labels that each got.

#2059 #2058 fix xml syntax error
  menas/ui/components/mappingTable/mappingTableDetail.view.xml
Labels: PR:tested

#2064 #2063: Add release notes for v2.27.1
  .github/CODEOWNERS
  _posts/2022-05-06-release-2.27.1.md
Labels: documentation

#2052 Feature/1693 api v3 schema etc
  rest-api/src/main/scala/za/co/absa/enceladus/rest_api/controllers/SchemaController.scala
  rest-api/src/main/scala/za/co/absa/enceladus/rest_api/controllers/v3/MappingTableControllerV3.scala
  rest-api/src/main/scala/za/co/absa/enceladus/rest_api/controllers/v3/PropertyDefinitionControllerV3.scala
  rest-api/src/main/scala/za/co/absa/enceladus/rest_api/controllers/v3/SchemaControllerV3.scala
  rest-api/src/main/scala/za/co/absa/enceladus/rest_api/controllers/v3/VersionedModelControllerV3.scala
  rest-api/src/main/scala/za/co/absa/enceladus/rest_api/services/SchemaService.scala
  rest-api/src/main/scala/za/co/absa/enceladus/rest_api/services/VersionedModelService.scala
  rest-api/src/main/scala/za/co/absa/enceladus/rest_api/services/v3/MappingTableServiceV3.scala
  rest-api/src/main/scala/za/co/absa/enceladus/rest_api/services/v3/SchemaServiceV3.scala
  rest-api/src/test/scala/za/co/absa/enceladus/rest_api/integration/controllers/BaseRestApiTest.scala
  rest-api/src/test/scala/za/co/absa/enceladus/rest_api/integration/controllers/v3/DatasetControllerV3IntegrationSuite.scala
  rest-api/src/test/scala/za/co/absa/enceladus/rest_api/integration/controllers/v3/MappingTableControllerV3IntegrationSuite.scala
  rest-api/src/test/scala/za/co/absa/enceladus/rest_api/integration/controllers/v3/PropertyDefinitionControllerV3IntegrationSuite.scala
  rest-api/src/test/scala/za/co/absa/enceladus/rest_api/integration/controllers/v3/SchemaControllerV3IntegrationSuite.scala
Labels: PR:tested

#2033 2031 spark partition sizing
  spark-jobs/pom.xml
  spark-jobs/src/main/resources/reference.conf
  spark-jobs/src/main/scala/za/co/absa/enceladus/common/CommonJobExecution.scala
  spark-jobs/src/main/scala/za/co/absa/enceladus/common/Repartitioner.scala
  spark-jobs/src/main/scala/za/co/absa/enceladus/common/config/CommonConfConstants.scala
  spark-jobs/src/main/scala/za/co/absa/enceladus/conformance/ConformanceExecution.scala
  spark-jobs/src/main/scala/za/co/absa/enceladus/standardization/StandardizationExecution.scala
  spark-jobs/src/test/scala/za/co/absa/enceladus/common/CommonExecutionSuite.scala
Labels: PR:no testing needed

#2049 2044 update to spark 3.2.1
  dao/src/main/scala/za/co/absa/enceladus/dao/rest/JsonSerializer.scala
  dao/src/test/scala/za/co/absa/enceladus/dao/rest/JsonSerializerSuite.scala
  data-model/src/main/scala/za/co/absa/enceladus/model/SchemaField.scala
  data-model/src/main/scala/za/co/absa/enceladus/model/test/factories/DatasetFactory.scala
  data-model/src/test/scala/za/co/absa/enceladus/model/conformanceRule/ConformanceRuleTest.scala
  migrations/pom.xml
  plugins-builtin/pom.xml
  plugins-builtin/src/main/scala/za/co/absa/enceladus/plugins/builtin/controlinfo/ControlInfoAvroSerializer.scala
  plugins-builtin/src/main/scala/za/co/absa/enceladus/plugins/builtin/errorsender/mq/KafkaErrorSenderPluginImpl.scala
  plugins-builtin/src/main/scala/za/co/absa/enceladus/plugins/builtin/errorsender/mq/kafka/KafkaErrorSenderPlugin.scala
  plugins-builtin/src/test/scala/za/co/absa/enceladus/plugins/builtin/errorsender/mq/KafkaErrorSenderPluginSuite.scala
  pom.xml
  rest-api/src/test/scala/za/co/absa/enceladus/rest_api/utils/parsers/SchemaParserSuite.scala
  spark-jobs/src/main/scala/za/co/absa/enceladus/conformance/interpreter/rules/CastingRuleInterpreter.scala
  spark-jobs/src/main/scala/za/co/absa/enceladus/conformance/interpreter/rules/NegationRuleInterpreter.scala
  spark-jobs/src/main/scala/za/co/absa/enceladus/conformance/interpreter/rules/mapping/MappingRuleInterpreter.scala
  spark-jobs/src/main/scala/za/co/absa/enceladus/conformance/interpreter/rules/mapping/MappingRuleInterpreterGroupExplode.scala
  spark-jobs/src/main/scala/za/co/absa/enceladus/standardization/interpreter/StandardizationInterpreter.scala
  spark-jobs/src/main/scala/za/co/absa/enceladus/standardization/interpreter/stages/TypeParser.scala
  spark-jobs/src/test/scala/za/co/absa/enceladus/standardization/interpreter/stages/TypeParserSuiteTemplate.scala
  utils/src/main/scala/za/co/absa/enceladus/utils/schema/SparkUtils.scala
  utils/src/main/scala/za/co/absa/enceladus/utils/transformations/ArrayTransformations.scala
  utils/src/test/scala/za/co/absa/enceladus/utils/transformations/ArrayTransformationsSuite.scala
Labels: PR:no testing needed

#2056 2042 kakfa plugin spark 3.2.1
  README.md
  dao/src/test/scala/za/co/absa/enceladus/dao/rest/JsonSerializerSuite.scala
  data-model/src/main/scala/za/co/absa/enceladus/model/Dataset.scala
  data-model/src/main/scala/za/co/absa/enceladus/model/MappingTable.scala
  data-model/src/main/scala/za/co/absa/enceladus/model/Schema.scala
  data-model/src/main/scala/za/co/absa/enceladus/model/properties/PropertyDefinition.scala
  data-model/src/main/scala/za/co/absa/enceladus/model/test/factories/DatasetFactory.scala
  data-model/src/main/scala/za/co/absa/enceladus/model/test/factories/MappingTableFactory.scala
  data-model/src/main/scala/za/co/absa/enceladus/model/test/factories/PropertyDefinitionFactory.scala
  data-model/src/main/scala/za/co/absa/enceladus/model/test/factories/SchemaFactory.scala
  data-model/src/main/scala/za/co/absa/enceladus/model/versionedModel/VersionedModel.scala
  menas/ui/components/dataset/datasetDetail.controller.js
  menas/ui/components/dataset/datasetDetail.view.xml
  menas/ui/components/mappingTable/mappingTableDetail.controller.js
  menas/ui/components/mappingTable/mappingTableDetail.view.xml
  menas/ui/components/property/datasetPropertyDetail.view.xml
  menas/ui/components/schema/schemaDetail.controller.js
  menas/ui/components/schema/schemaDetail.view.xml
  menas/ui/generic/formatters.js
  menas/ui/service/EntityService.js
  menas/ui/service/MonitoringService.js
  menas/ui/service/PropertiesService.js
  plugins-builtin/pom.xml
  plugins-builtin/src/main/scala/za/co/absa/enceladus/plugins/builtin/common/mq/kafka/InfoProducerKafka.scala
  plugins-builtin/src/main/scala/za/co/absa/enceladus/plugins/builtin/controlinfo/mq/ControlInfoSenderPlugin.scala
  plugins-builtin/src/main/scala/za/co/absa/enceladus/plugins/builtin/errorsender/DceError.scala
  plugins-builtin/src/main/scala/za/co/absa/enceladus/plugins/builtin/errorsender/mq/KafkaErrorSenderPluginImpl.scala
  plugins-builtin/src/main/scala/za/co/absa/enceladus/plugins/builtin/errorsender/mq/kafka/KafkaErrorSenderPlugin.scala
  plugins-builtin/src/test/scala/za/co/absa/enceladus/plugins/builtin/errorsender/mq/KafkaErrorSenderPluginSuite.scala
  pom.xml
  rest-api/src/main/resources/application.properties.template
  rest-api/src/main/scala/za/co/absa/enceladus/rest_api/controllers/RestExceptionHandler.scala
  rest-api/src/main/scala/za/co/absa/enceladus/rest_api/controllers/VersionedModelController.scala
  rest-api/src/main/scala/za/co/absa/enceladus/rest_api/exceptions/LockedEntityException.scala
  rest-api/src/main/scala/za/co/absa/enceladus/rest_api/repositories/MonitoringMongoRepository.scala
  rest-api/src/main/scala/za/co/absa/enceladus/rest_api/repositories/VersionedMongoRepository.scala
  rest-api/src/main/scala/za/co/absa/enceladus/rest_api/services/DatasetService.scala
  rest-api/src/main/scala/za/co/absa/enceladus/rest_api/services/VersionedModelService.scala
  rest-api/src/test/scala/za/co/absa/enceladus/rest_api/integration/controllers/PropertyDefinitionApiIntegrationSuite.scala
  rest-api/src/test/scala/za/co/absa/enceladus/rest_api/integration/controllers/package.scala
  rest-api/src/test/scala/za/co/absa/enceladus/rest_api/integration/repositories/DatasetRepositoryIntegrationSuite.scala
  rest-api/src/test/scala/za/co/absa/enceladus/rest_api/integration/repositories/StatisticsIntegrationSuite.scala
  rest-api/src/test/scala/za/co/absa/enceladus/rest_api/services/DatasetServiceTest.scala
  scripts/migration/constants.py
  scripts/migration/initialize_menas.py
  scripts/migration/menas_db.py
  scripts/migration/migrate_menas.py
  scripts/migration/requirements.txt
  spark-jobs/src/main/scala/za/co/absa/enceladus/common/CommonJobExecution.scala
  spark-jobs/src/main/scala/za/co/absa/enceladus/common/version/SparkVersionGuard.scala
  spark-jobs/src/main/scala/za/co/absa/enceladus/conformance/HyperConformance.scala
  spark-jobs/src/test/scala/za/co/absa/enceladus/common/CommonExecutionSuite.scala
  spark-jobs/src/test/scala/za/co/absa/enceladus/common/version/SparkVersionGuardSuite.scala
  spark-jobs/src/test/scala/za/co/absa/enceladus/conformance/config/ConformanceParserSuite.scala
  spark-jobs/src/test/scala/za/co/absa/enceladus/standardization/config/StandardizationParserSuite.scala
  utils/src/main/scala/za/co/absa/enceladus/utils/config/ConfigUtils.scala
  utils/src/main/scala/za/co/absa/enceladus/utils/config/SecureConfig.scala
  utils/src/test/resources/config/existingFile.ext
  utils/src/test/scala/za/co/absa/enceladus/utils/config/SecureConfigSuite.scala
Labels: PR:tested

#2066 Feature/1693 api v3 disabled fails validation
  rest-api/src/main/scala/za/co/absa/enceladus/rest_api/controllers/RestExceptionHandler.scala
  rest-api/src/main/scala/za/co/absa/enceladus/rest_api/controllers/VersionedModelController.scala
  rest-api/src/main/scala/za/co/absa/enceladus/rest_api/controllers/v3/VersionedModelControllerV3.scala
  rest-api/src/main/scala/za/co/absa/enceladus/rest_api/exceptions/EntityDisabledException.scala
  rest-api/src/main/scala/za/co/absa/enceladus/rest_api/services/AttachmentService.scala
  rest-api/src/main/scala/za/co/absa/enceladus/rest_api/services/DatasetService.scala
  rest-api/src/main/scala/za/co/absa/enceladus/rest_api/services/MappingTableService.scala
  rest-api/src/main/scala/za/co/absa/enceladus/rest_api/services/ModelService.scala
  rest-api/src/main/scala/za/co/absa/enceladus/rest_api/services/MonitoringService.scala
  rest-api/src/main/scala/za/co/absa/enceladus/rest_api/services/PropertyDefinitionService.scala
  rest-api/src/main/scala/za/co/absa/enceladus/rest_api/services/RunService.scala
  rest-api/src/main/scala/za/co/absa/enceladus/rest_api/services/SchemaService.scala
  rest-api/src/main/scala/za/co/absa/enceladus/rest_api/services/VersionedModelService.scala
  rest-api/src/main/scala/za/co/absa/enceladus/rest_api/services/v3/DatasetServiceV3.scala
  rest-api/src/main/scala/za/co/absa/enceladus/rest_api/services/v3/MappingTableServiceV3.scala
  rest-api/src/main/scala/za/co/absa/enceladus/rest_api/services/v3/PropertyDefinitionServiceV3.scala
  rest-api/src/main/scala/za/co/absa/enceladus/rest_api/services/v3/SchemaServiceV3.scala
  rest-api/src/main/scala/za/co/absa/enceladus/rest_api/services/v3/VersionedModelServiceV3.scala
  rest-api/src/test/scala/za/co/absa/enceladus/rest_api/integration/controllers/DatasetApiIntegrationSuite.scala
  rest-api/src/test/scala/za/co/absa/enceladus/rest_api/integration/controllers/v3/DatasetControllerV3IntegrationSuite.scala
  rest-api/src/test/scala/za/co/absa/enceladus/rest_api/integration/controllers/v3/MappingTableControllerV3IntegrationSuite.scala
  rest-api/src/test/scala/za/co/absa/enceladus/rest_api/integration/controllers/v3/PropertyDefinitionControllerV3IntegrationSuite.scala
  rest-api/src/test/scala/za/co/absa/enceladus/rest_api/integration/controllers/v3/SchemaControllerV3IntegrationSuite.scala
Labels: PR:tested
