Repository AbsaOSS/enceladus, pull requests merged in 2022-08, with the labels that each got.

#2101 #2091: Create a documentation folder for Enceladus 3
  .github/CODEOWNERS
  README.md
  _data/configuration_3_0_0.yml
  _data/menas-configuration_3_0_0.yml
  _data/selected-plugins-configuration_3_0_0.yml
  _data/versions.yaml
  _docs/3.0.0/build-process.md
  _docs/3.0.0/components.md
  _docs/3.0.0/components/menas.md
  _docs/3.0.0/deployment.md
  _docs/3.0.0/plugins-built-in.md
  _docs/3.0.0/plugins.md
  _docs/3.0.0/usage.md
  _docs/3.0.0/usage/config.md
  _docs/3.0.0/usage/data-quick-start.md
  _docs/3.0.0/usage/errcol.md
  _docs/3.0.0/usage/info-file.md
  _docs/3.0.0/usage/menas-api.md
  _docs/3.0.0/usage/menas-config.md
  _docs/3.0.0/usage/menas-conformance-rules.md
  _docs/3.0.0/usage/menas-quick-start.md
  _docs/3.0.0/usage/run.md
  _docs/3.0.0/usage/schema.md
  _docs/3.0.0/usage/spark-jobs-quick-start.md
  _docs/3.0.0/usage/standardization-formats.md
Labels: documentation

#2103 GHP: Rest API v3 desc
  Gemfile.lock
  _docs/2.0.0/usage/menas-api.md
  _docs/3.0.0/usage.md
  _docs/3.0.0/usage/menas-api.md
  _docs/3.0.0/usage/rest-api.md
Labels: documentation

#2098 #2090: Integrate Spark-Commons 0.3.x
  examples/src/test/resources/log4j.properties
  pom.xml
  spark-jobs/src/main/scala/za/co/absa/enceladus/conformance/interpreter/DynamicInterpreter.scala
  spark-jobs/src/main/scala/za/co/absa/enceladus/conformance/interpreter/OptimizerTimeTracker.scala
  spark-jobs/src/test/resources/log4j.properties
  spark-jobs/src/test/scala/za/co/absa/enceladus/conformance/interpreter/InterpreterSuite.scala
  spark-jobs/src/test/scala/za/co/absa/enceladus/conformance/interpreter/rules/CastingRuleSuite.scala
  spark-jobs/src/test/scala/za/co/absa/enceladus/conformance/interpreter/rules/NegationRuleSuite.scala
  spark-jobs/src/test/scala/za/co/absa/enceladus/conformance/interpreter/rules/mapping/MappingGroupExplodeSuite.scala
  spark-jobs/src/test/scala/za/co/absa/enceladus/conformance/interpreter/rules/mapping/MappingRuleBroadcastSuite.scala
  spark-jobs/src/test/scala/za/co/absa/enceladus/conformance/interpreter/rules/mapping/MappingRuleSuite.scala
  spark-jobs/src/test/scala/za/co/absa/enceladus/standardization/StandardizationRerunSuite.scala
  spark-jobs/src/test/scala/za/co/absa/enceladus/standardization/interpreter/CounterPartySuite.scala
  spark-jobs/src/test/scala/za/co/absa/enceladus/standardization/interpreter/StandardizationInterpreterSuite.scala
  spark-jobs/src/test/scala/za/co/absa/enceladus/standardization/interpreter/StandardizationInterpreter_ArraySuite.scala
  spark-jobs/src/test/scala/za/co/absa/enceladus/standardization/interpreter/StandardizationInterpreter_BinarySuite.scala
  spark-jobs/src/test/scala/za/co/absa/enceladus/standardization/interpreter/StandardizationInterpreter_DateSuite.scala
  spark-jobs/src/test/scala/za/co/absa/enceladus/standardization/interpreter/StandardizationInterpreter_DecimalSuite.scala
  spark-jobs/src/test/scala/za/co/absa/enceladus/standardization/interpreter/StandardizationInterpreter_FractionalSuite.scala
  spark-jobs/src/test/scala/za/co/absa/enceladus/standardization/interpreter/StandardizationInterpreter_IntegralSuite.scala
  spark-jobs/src/test/scala/za/co/absa/enceladus/standardization/interpreter/StandardizationInterpreter_TimestampSuite.scala
  utils/pom.xml
  utils/src/main/scala/za/co/absa/enceladus/utils/testUtils/TZNormalizedSparkTestBase.scala
  utils/src/main/scala/za/co/absa/enceladus/utils/types/TypedStructField.scala
  utils/src/test/scala/za/co/absa/enceladus/utils/broadcast/LocalMappingTableSuite.scala
Labels: PR:no testing needed

#2102 #2092 swagger doc: fix for runs + readme description enhanced
  README.md
  rest-api/src/main/scala/za/co/absa/enceladus/rest_api/SpringFoxConfig.scala
Labels: PR:tested, documentation

#2108 #2105 Change `menas.rest` to `enceladus.rest` in Github Pages
  _data/configuration_3_0_0.yml
  _docs/3.0.0/usage/run.md
Labels: documentation

#2115 #2112 Fix `and` and `or` functions in DataFrameFilter
  data-model/src/main/scala/za/co/absa/enceladus/model/dataFrameFilter/package.scala
  data-model/src/test/scala/za/co/absa/enceladus/model/dataFrameFilter/DataFrameFilterSuite.scala
Labels: PR:tested

#2107 #2105 Change spark-jobs config keys prefix from `menas.rest` to `enceladus.rest`
  README.md
  examples/data/e2e_tests/test_jsons/castingConformanceRuleTest.json
  examples/data/e2e_tests/test_jsons/coalesceConformanceRuleTest.json
  examples/data/e2e_tests/test_jsons/concatenationConformanceRuleTest.json
  examples/data/e2e_tests/test_jsons/literalConformanceRuleTest.json
  examples/data/e2e_tests/test_jsons/mappingConformanceRuleTest.json
  examples/data/e2e_tests/test_jsons/negationConformanceRuleTest.json
  examples/data/e2e_tests/test_jsons/singleColumnConformanceRuleTest.json
  examples/data/e2e_tests/test_jsons/stdNfDnTest.json
  examples/data/e2e_tests/test_jsons/stdNfDyTest.json
  examples/data/e2e_tests/test_jsons/stdNtDnTest.json
  examples/data/e2e_tests/test_jsons/stdNtDyTest.json
  examples/data/e2e_tests/test_jsons/uppercaseConformanceRuleTest.json
  examples/src/main/resources/application.conf.template
  examples/src/main/scala/za/co/absa/enceladus/examples/CustomRuleSample2.scala
  examples/src/main/scala/za/co/absa/enceladus/examples/CustomRuleSample3.scala
  examples/src/main/scala/za/co/absa/enceladus/examples/CustomRuleSample4.scala
  examples/src/test/scala/za/co/absa/enceladus/examples/interpreter/rules/custom/XPadCustomConformanceRuleSuite.scala
  rest-api/src/main/resources/scheduling/oozie/workflow_template.xml
  spark-jobs/src/main/resources/reference.conf
  spark-jobs/src/main/scala/za/co/absa/enceladus/common/CommonJobExecution.scala
  spark-jobs/src/main/scala/za/co/absa/enceladus/conformance/HyperConformance.scala
  spark-jobs/src/main/scala/za/co/absa/enceladus/conformance/HyperConformanceAttributes.scala
  spark-jobs/src/test/resources/application.conf
Labels: PR:tested
