Repository AbsaOSS/enceladus, pull requests merged in 2023-03, with the labels that each got.

#2176 #2151 Remove hardcoded spline from Enceladus
  README.md
  menas/ui/components/run/runDetail.view.xml
  menas/ui/index.html
  menas/ui/package.json
  menas/ui/service/RunRestDAO.js
  menas/ui/service/RunService.js
  pom.xml
  scripts/bash/enceladus_env.template.sh
  scripts/bash/run_enceladus.sh
  spark-jobs/pom.xml
  spark-jobs/src/main/resources/reference.conf
  spark-jobs/src/main/scala/za/co/absa/enceladus/common/CommonJobExecution.scala
  spark-jobs/src/test/scala/za/co/absa/enceladus/conformance/interpreter/rules/custom/CustomRuleSuite.scala
Labels: PR:tested

#2178 Feature/2160 openapi3
  README.md
  dao/src/test/scala/za/co/absa/enceladus/dao/rest/JsonSerializerSuite.scala
  data-model/pom.xml
  data-model/src/main/scala/za/co/absa/enceladus/model/Dataset.scala
  data-model/src/main/scala/za/co/absa/enceladus/model/DefaultValue.scala
  data-model/src/main/scala/za/co/absa/enceladus/model/MappingTable.scala
  data-model/src/main/scala/za/co/absa/enceladus/model/Schema.scala
  data-model/src/main/scala/za/co/absa/enceladus/model/SchemaField.scala
  data-model/src/main/scala/za/co/absa/enceladus/model/Validation.scala
  data-model/src/main/scala/za/co/absa/enceladus/model/backend/Reference.scala
  data-model/src/main/scala/za/co/absa/enceladus/model/conformanceRule/package.scala
  data-model/src/main/scala/za/co/absa/enceladus/model/properties/PropertyDefinition.scala
  data-model/src/main/scala/za/co/absa/enceladus/model/versionedModel/VersionedModel.scala
  pom.xml
  rest-api/pom.xml
  rest-api/src/main/resources/application.properties.template
  rest-api/src/main/scala/za/co/absa/enceladus/rest_api/Application.scala
  rest-api/src/main/scala/za/co/absa/enceladus/rest_api/SpringFoxConfig.scala
  rest-api/src/main/scala/za/co/absa/enceladus/rest_api/SwaggerConfig.scala
  rest-api/src/main/scala/za/co/absa/enceladus/rest_api/WebSecurityConfig.scala
  rest-api/src/main/scala/za/co/absa/enceladus/rest_api/controllers/DatasetController.scala
  rest-api/src/main/scala/za/co/absa/enceladus/rest_api/controllers/MappingTableController.scala
  rest-api/src/main/scala/za/co/absa/enceladus/rest_api/controllers/MonitoringController.scala
  rest-api/src/main/scala/za/co/absa/enceladus/rest_api/controllers/PropertyDefinitionController.scala
  rest-api/src/main/scala/za/co/absa/enceladus/rest_api/controllers/RunController.scala
  rest-api/src/main/scala/za/co/absa/enceladus/rest_api/controllers/SchemaController.scala
  rest-api/src/main/scala/za/co/absa/enceladus/rest_api/controllers/SparkController.scala
  rest-api/src/main/scala/za/co/absa/enceladus/rest_api/controllers/UserInfoController.scala
  rest-api/src/main/scala/za/co/absa/enceladus/rest_api/controllers/VersionedModelController.scala
  rest-api/src/main/scala/za/co/absa/enceladus/rest_api/controllers/v3/DatasetControllerV3.scala
  rest-api/src/main/scala/za/co/absa/enceladus/rest_api/controllers/v3/MappingTableControllerV3.scala
  rest-api/src/main/scala/za/co/absa/enceladus/rest_api/controllers/v3/PropertyDefinitionControllerV3.scala
  rest-api/src/main/scala/za/co/absa/enceladus/rest_api/controllers/v3/RunControllerV3.scala
  rest-api/src/main/scala/za/co/absa/enceladus/rest_api/controllers/v3/SchemaControllerV3.scala
  rest-api/src/main/scala/za/co/absa/enceladus/rest_api/controllers/v3/VersionedModelControllerV3.scala
  rest-api/src/main/scala/za/co/absa/enceladus/rest_api/services/DatasetService.scala
  rest-api/src/main/scala/za/co/absa/enceladus/rest_api/services/MappingTableService.scala
  spark-jobs/src/main/scala/za/co/absa/enceladus/conformance/interpreter/rules/mapping/CommonMappingRuleInterpreter.scala
Labels: PR:tested

#2173 #2172 - update hermes json files
  examples/data/e2e_tests/test_jsons/castingConformanceRuleTest.json
  examples/data/e2e_tests/test_jsons/coalesceConformanceRuleTest.json
  examples/data/e2e_tests/test_jsons/concatenationConformanceRuleTest.json
  examples/data/e2e_tests/test_jsons/literalConformanceRuleTest.json
  examples/data/e2e_tests/test_jsons/mappingConformanceRuleTest.json
  examples/data/e2e_tests/test_jsons/negationConformanceRuleTest.json
  examples/data/e2e_tests/test_jsons/singleColumnConformanceRuleTest.json
  examples/data/e2e_tests/test_jsons/stdNfDnTest.json
  examples/data/e2e_tests/test_jsons/stdNfDyTest.json
  examples/data/e2e_tests/test_jsons/stdNtDnTest.json
  examples/data/e2e_tests/test_jsons/stdNtDyTest.json
  examples/data/e2e_tests/test_jsons/uppercaseConformanceRuleTest.json
Labels: PR:no testing needed

#2181 #2180 multiline annotations squashed to single line.
  dao/pom.xml
  data-model/pom.xml
  data-model/src/main/scala/za/co/absa/enceladus/model/Dataset.scala
  data-model/src/main/scala/za/co/absa/enceladus/model/MappingTable.scala
  data-model/src/main/scala/za/co/absa/enceladus/model/backend/Reference.scala
  data-model/src/main/scala/za/co/absa/enceladus/model/conformanceRule/package.scala
  menas/pom.xml
  migrations-cli/pom.xml
  migrations/pom.xml
  plugins-api/pom.xml
  plugins-builtin/pom.xml
  pom.xml
  rest-api/pom.xml
  spark-jobs/pom.xml
  utils/pom.xml
Labels: PR:tested

#2183 #2182 fixing unmoored doc, reverting to 3.0.0-SNAPSHOT
  dao/pom.xml
  dao/src/main/scala/za/co/absa/enceladus/dao/rest/RestClient.scala
  data-model/pom.xml
  menas/pom.xml
  migrations-cli/pom.xml
  migrations/pom.xml
  plugins-api/pom.xml
  plugins-builtin/pom.xml
  pom.xml
  rest-api/pom.xml
  spark-jobs/pom.xml
  utils/pom.xml
Labels: PR:tested

#2186 #2185 - Missing project support for chip M1
  menas/pom.xml
  menas/ui/components/mappingTable/filterEdit/FilterEdit.js
  menas/ui/service/FilterTreeUtils.js
  rest-api/pom.xml
  rest-api/src/test/scala/za/co/absa/enceladus/rest_api/integration/mongo/EmbeddedMongo.scala
Labels: PR:tested

#2187 #2179 Add release notes for v3.0.0
  .github/CODEOWNERS
  _posts/2023-03-23-release-3.0.0.md
  utils/create_docs/docs.rb
Labels: docs
